KB = [
 {"title":"VPN Troubleshooting Guide","category":"Network","text":"vpn cannot connect client credentials internet reconnect authentication","steps":["Disconnect your current VPN session","Restart the VPN client","Verify your internet connection","Reconnect with your company credentials","If it still fails, contact IT support"]},
 {"title":"Password Reset Guide","category":"Account & Access","text":"forgot password reset login locked account sign in","steps":["Open the self-service portal","Choose 'Forgot password'","Verify with the code sent to your registered phone or email","Set a new password (12+ characters)","Sign in again on all devices"]},
 {"title":"Wi-Fi Troubleshooting Guide","category":"Network","text":"wifi wi-fi wireless internet network slow disconnect","steps":["Toggle Wi-Fi off and on","Forget and rejoin the network","Restart your router or laptop","Run the network diagnostics tool"]},
 {"title":"Email Troubleshooting Guide","category":"Email","text":"email outlook mailbox cannot send receive inbox","steps":["Check webmail to isolate the client","Restart Outlook in safe mode","Rebuild your mail profile","Confirm mailbox quota"]},
 {"title":"Laptop & Hardware Guide","category":"Hardware","text":"mouse keyboard laptop monitor printer usb bluetooth battery","steps":["Check cable or battery","Try another USB port","Re-pair Bluetooth devices","Restart the device and update drivers"]},
 {"title":"Software Installation Guide","category":"Software","text":"install software license application request","steps":["Open the Company Software Center","Request the app","Wait for manager approval","Install from the Software Center"]},
 {"title":"Security Incident Procedure","category":"Security","text":"suspicious phishing malware virus hacked password email link","steps":["Do not click links or reply","Report with the Phish Alert button","Security team investigates sender and scope"]},
 {"title":"Server Incident Response Guide","category":"Infrastructure","text":"production server down outage customers unavailable website","steps":["Declare an incident","Page the on-call DevOps engineer","Check health dashboards and recent deploys","Human approval before any rollback"]},
 {"title":"Database Troubleshooting Guide","category":"Database","text":"database sql query slow locks connections","steps":["Check connections and locks","Review the slow query log","DBA approval before any change"]},
]
